export const FETCH_SCORE_LIST_REQUEST = "FETCH_SCORE_LIST_REQUEST";
export const FETCH_SCORE_LIST_SUCCESS = "FETCH_SCORE_LIST_SUCCESS";
export const FETCH_SCORE_LIST_FAILURE = "FETCH_SCORE_LIST_FAILURE";
